name: Main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dprint check
        uses: dprint/check@v2.2
        with:
          dprint-version: 0.45.1

  pulumi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pulumi login
        uses: pulumi/auth-actions@v1
        with:
          organization: UnstoppableMango
          requested-token-type: urn:pulumi:token-type:access_token:personal

      - uses: pulumi/actions@v5
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          stack-name: UnstoppableMango/github
          refresh: true
          work-dir: src
